version: '3.1'

services:

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: rio
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 8003:5432
